version: '3.7'
services:

# Nginx reverse proxy :
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 4100:4100
    depends_on:
      - ms-auth
      - ms-restaurant
      - ms-order

# Backend databases :
  db-mysql:
    container_name: db-mysql
    restart: unless-stopped
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dbusers
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=rootsecret
      - MYSQL_USER=msauth
      - MYSQL_PASSWORD=msauthsecret
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql

  db-mongodb:
    image: mongo:latest
    container_name: db-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"

# Backend Microservices :
  ms-auth-v1:
    container_name: ms-auth-v1
    restart: unless-stopped
    environment:
      - NODE_ENV=DOCKER
      - DATABASE_URL=mysql://root:rootsecret@db-mysql/dbusers
    build:
        context: ./apps/ms-auth/
    depends_on:
      - db-mysql
      - ms-restaurant

  ms-auth-v2:
    container_name: ms-auth-v2
    restart: unless-stopped
    environment:
      - NODE_ENV=DOCKER
      - DATABASE_URL=mysql://root:rootsecret@db-mysql/dbusers
    build:
        context: ./apps/ms-auth/
    depends_on:
      - db-mysql
      - ms-restaurant

  ms-restaurant-v1:
    container_name: ms-restaurant-v1
    restart: unless-stopped
    environment:
      - NODE_ENV=DOCKER
      - DATABASE_URL=mongodb://db-mongodb:27017
    build:
        context: ./apps/ms-restaurant/
    depends_on:
      - db-mongodb

  ms-restaurant-v2:
    container_name: ms-restaurant-v2
    restart: unless-stopped
    environment:
      - NODE_ENV=DOCKER
      - DATABASE_URL=mongodb://db-mongodb:27017
    build:
        context: ./apps/ms-restaurant/
    depends_on:
      - db-mongodb

  ms-order-v1:
    container_name: ms-order-v1
    restart: unless-stopped
    environment:
      - NODE_ENV=DOCKER
      - DATABASE_URL=mongodb://db-mongodb:27017
    build:
        context: ./apps/ms-order/
    depends_on:
      - db-mongodb

  ms-order-v2:
    container_name: ms-order-v2
    restart: unless-stopped
    environment:
      - NODE_ENV=DOCKER
      - DATABASE_URL=mongodb://db-mongodb:27017
    build:
        context: ./apps/ms-order/
    depends_on:
      - db-mongodb
